name: Create Release

on:
  push:
    branches:
      - main


permissions:
  contents: write

jobs:
  build-create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get latest release tag
        id: get_latest
        run: |
          latest_tag=$(gh release view --json tagName -q .tagName || echo "v0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate next patch version
        id: bump
        run: |
          tag=${{ steps.get_latest.outputs.latest_tag }}
          version=${tag#v}

          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))

          new_tag="v$major.$minor.$patch"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create new tag
        run: |
          git tag ${{ steps.bump.outputs.new_tag }}
          git push origin ${{ steps.bump.outputs.new_tag }}
      
      - name: Get repo name
        id: repo_name
        run: echo "REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | sed -e "s/:refs//")" >> $GITHUB_OUTPUT

      - name: Build a release
        run: |
          bash create_release.sh ${{ steps.bump.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ steps.repo_name.outputs.REPOSITORY_NAME }}
